#remove comments from below rows and remove comment from App.java row 83 to start on HTTPS

server.port: 8090
#server.ssl.key-store: kohls_keystore.jks
#server.ssl.key-store-password: pa$$w0rd
#server.ssl.keyStoreType: JKS
#server.ssl.keyAlias: kohls

#Hawt.io configurations. Example: http://localhost:8091/management/actuator/hawtio/console
management:
  server:
    port: 8091
    servlet:
      context-path: /management
  endpoints:
    web:
      # customize the /actuator path
      #      base-path:
      # customize the path to the Hawtio endpoint
      path-mapping.hawtio: hawtio/console
      exposure:
        #Enable the Hawtio and Jolokia endpoints
        include: hawtio,jolokia
hawtio:
  authenticationEnabled: false
  proxyWhitelist: '*'

#hawt.io and Jolokia properties
endpoints.jolokia.sensitive: false
spring.jmx.enabled: true
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
spring:
  jpa:
    show-sql: true

spring.jackson.serialization.indent_output: true

#H2 web console
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

security:
  basic:
    enabled: true
    authorize-mode: NONE

custom:
  pesho: test
  "yes": Yes, Sir!
  !!str no: Nope!
